### ISSUE TITLE
when selecting integrated only it selects discrete only

### ISSUE THREAD

**Issue by wikkidtt** [codykrieger/gfxCardStatus#372] opened 2021-09-20 17:46 UTC
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  System Firmware Version:	1715.40.7.0.0 (iBridge: 19.16.10506.5.1,0)
  OS Loader Version:	540~34
  Activation Lock Status:	Enabled

**Comment by codykrieger** [comment] 2021-09-28 02:33
Thanks for the report. This sounds like a dupe of #354 / #331  / #321. Closing in favor of one of those.

**Closed as completed by codykrieger** 2021-09-28 02:33 UTC
