### ISSUE TITLE
Selecting integrated only activates discrete card?

### ISSUE THREAD

**Issue by dannyhollman** [codykrieger/gfxCardStatus#279] opened 2017-05-25 18:11 UTC
My 2011 macbook pro is once again suffering from GPU kernel panics.  Whenever I click integrated only my computer immediately crashes.  These crashes only seems to happen when the discrete card is activated, leading me to believe gfxCardStatus is activating the card when selecting integrated only. Is anyone else having this issue or know of a fix?

**Comment by codykrieger** [comment] 2017-05-26 02:07
Dupe of #242.

**Closed by codykrieger** 2017-05-26 02:07 UTC
