### ISSUE TITLE
Switching problem

### ISSUE THREAD

**Issue by rronbajri** [codykrieger/gfxCardStatus#288] opened 2017-08-01 08:36 UTC
I just updated my system to Sierra and discovered that I have a problem with gfxCardStatus. The switching warning is telling me to close gfxCardStatus in order to Switch to Integrated. Did anyone else had this problem?

**Comment by codykrieger** [comment] 2017-08-01 15:15
Dupe of #162.

**Closed by codykrieger** 2017-08-01 15:15 UTC
