### ISSUE TITLE
Dependency for integrated only is gfxCardStatus

### ISSUE THREAD

**Issue by mbp10** [codykrieger/gfxCardStatus#190] opened 2015-01-23 14:09 UTC
I am using the gfxCardStatus , v 2.3 on macbook pro mid-2010 running yosemite.  I loaded this utility following a suggested work around for a GPU panic. I am not able to chose "integrated only" because the gfxCardStatus itself shows up as a dependency.

**Comment by codykrieger** [comment] 2015-01-23 18:29
Dupe of #162.

**Closed by codykrieger** 2015-01-23 18:29 UTC
