### ISSUE TITLE
Only works in Discrete after upgrade to OS Sierra

### ISSUE THREAD

**Issue by jemoreto** [codykrieger/gfxCardStatus#254] opened 2016-10-12 14:00 UTC
Hello guys, the card only works in Discrete mode after upgrade to MacOS Sierra. 

Can'tSwitchToIntegratedOnlyPlural
gfxCardStatus

Thanks

**Comment by codykrieger** [comment] 2016-10-12 15:33
Duplicate of #240.

**Closed by codykrieger** 2016-10-12 15:33 UTC
