### ISSUE TITLE
sleep after 'integrated only' leads to inconsistent mode/display

### ISSUE THREAD

**Issue by sparr** [codykrieger/gfxCardStatus#201] opened 2015-05-26 14:01 UTC
Using OSX 10.9.5 I often use the 'integrated only' setting to conserve battery. If my machine goes to sleep (and possibly some other criteria) then later when I wake it up it will say it's in 'dynamic switching' mode, but it won't switch to the dedicated graphics card when I run a game or plug in an external monitor. I have to click 'integrated only' again (to switch "out" of dynamic switching mode) then click 'dynamic switching', then it works fine.

**Comment by codykrieger** [comment] 2015-05-26 17:57
Dupe of #109.

**Closed by codykrieger** 2015-05-26 17:57 UTC
