### ISSUE TITLE
gfxCardStatus shows integrated GPU when Discrete is checked in the menu

### ISSUE THREAD

**Issue by wtholliday** [codykrieger/gfxCardStatus#264] opened 2017-01-15 23:10 UTC
This is confusing:

<img width="262" alt="screen shot 2017-01-15 at 2 58 56 pm" src="https://cloud.githubusercontent.com/assets/841144/21967042/6f0142e6-db34-11e6-8e06-40a379ca0cb2.png">

macOS 10.12.2
MacBook Pro (Retina, 15-inch, Late 2013)

**Comment by codykrieger** [comment] 2017-01-15 23:25
Dupe of #240.

**Closed by codykrieger** 2017-01-15 23:25 UTC
