### ISSUE TITLE
issue with switch integrated graphics

### ISSUE THREAD

**Issue by aledanto** [codykrieger/gfxCardStatus#265] opened 2017-01-22 02:46 UTC
I can't switch an integrated card.
i have a MacBook Pro 15" early 2011 with the intel graphics 3000 and AMD radeon.
![schermata 2017-01-22 alle 03 38 36](https://cloud.githubusercontent.com/assets/25274516/22179470/4bdb6398-e055-11e6-8506-6ef2b5d5209a.png)

**Comment by codykrieger** [comment] 2017-01-22 02:47
Dupe of #240.

**Closed by codykrieger** 2017-01-22 02:47 UTC
