### ISSUE TITLE
not able to switch to Integrated Only

### ISSUE THREAD

**Issue by djarecka** [codykrieger/gfxCardStatus#319] opened 2019-02-28 20:22 UTC
I have MacBook Pro (Retina, Mid 2012) and OSX 10.12.1 and recently installed gfxCard Status (v 2.3), but I have problem with switching to Integrated Only (even if nothing is using the Discrete card). It simply mark `Integrated only` for 2 seconds and jump to `Discrete only` (no warnings or errors)

**Comment by tentac94** [comment] 2019-03-12 09:34
Hello, 
Just a quick comment to tell that I have the exact same issue with a brend new MBP 15 inches with Radeon Pro Vega 20.
I can force Discrete, I can set automatic switching, both work fine
but when I try and activate integrated only, it switches to discrete (even when it was previously running on integrated). This is not a  wrong reported status as for #312 since when I check the GC on the "about this mac" menu, it says that it is running on discrete
in the end, gfx then acts only as an information tool on which GC i am running, since I cannot force integrated.

Any Idea ? this is such a pity since the app is really great otherwise, and there is no alternative :(

best and thanks !

Tentac

**Comment by codykrieger** [comment] 2019-03-16 10:20
Dupe of #310 and associated issues.

**Closed by codykrieger** 2019-03-16 10:20 UTC
