### ISSUE TITLE
On High Sierra, UI problem on selection

### ISSUE THREAD

**Issue by alessandro308** [codykrieger/gfxCardStatus#292] opened 2017-10-10 12:28 UTC
On HighSierra, after selected "Integrated Only" and the icon "i" appears in menu, if I open a tab, a Discrete Only option is selected but Intel card is running.

I attach the screenshot
![screen shot 2017-10-10 at 14 26 53](https://user-images.githubusercontent.com/6088300/31386519-52a8727a-adc7-11e7-9422-7ed1fa7e1032.png)

**Comment by codykrieger** [comment] 2017-10-10 18:51
Dupe of #103.

**Closed by codykrieger** 2017-10-10 18:51 UTC

**Comment by LOBOtechnic** [comment] 2017-12-04 17:31
Is this really a duplicate?  I didn't have this behaviour until I updated to High Sierra today.  No matter how many times I select integrated, it says discrete only.  Issue 103 indicates it just takes 2 attempts.
