### ISSUE TITLE
macOS High Sierra breaks the app yet again

### ISSUE THREAD

**Issue by ipoznyak** [codykrieger/gfxCardStatus#282] opened 2017-06-28 23:31 UTC
Long story short: none of the current versions (I tried 1.7, 2.3, and two latest forks) work in High Sierra Beta. Anyone can take a look at it?

**Comment by maciboy** [comment] 2017-07-28 19:45
With DP4 everything works fine for me on my MBP 15“ 2010 with the release from Steve: https://github.com/steveschow/gfxCardStatus

**Comment by AlexChambers** [comment] 2017-07-29 06:23
@ipoznyak What's the long story to this problem? Is it still persistent?

**Comment by ipoznyak** [comment] 2017-07-29 06:30
@AlexChambers I don't know the problem is still there since I did a hardware fix for my MBP 2010 (capacitor change) and I don't need this utility anymore :)

**Comment by dunarri** [comment] 2017-07-31 19:40
@ipoznyak Could you tell us how you did the hardware fix?
I'd like to try on my MBP since it crashes every day even running the fork.

**Comment by ipoznyak** [comment] 2017-07-31 19:49
@dunarri check out this video: https://www.youtube.com/watch?v=DzcgT_fiVTA
You just need to change one capacitor on the motherboard and you're all done. The capacity of the capacitor could be anything from 220 to 470 (I used 330) as long as it is no more then 2-2.5V. Find someone experienced who can solder for you.

**Comment by dunarri** [comment] 2017-07-31 20:38
Thanks. Luckily I am someone experienced who can solder, just need to purchase the replacement capacitor.

**Comment by ipoznyak** [comment] 2017-07-31 20:40
@dunarri well then you must be familiar with everything going on in that youtube video. Good luck!

**Comment by HackintoshHD** [comment] 2017-09-27 06:55
On a MacBook Pro Mid-2009 (macbookpro5,2) with macOS 10.13.0 (Build 17A365), gfxCardStatus 2.3 will still launch, but the menu entry for the card only has a generic "card" entry instead of the name of the particular card.

Switching GPUs will simply have no effect at all (the "i" icon does not turn into the "d" icon and GPUs are obviously not switched).

**Comment by hoc-genebygene** [comment] 2017-11-03 06:18
Works great for me.

2016 Touchbar 15" (Radeon Pro 460).

**Comment by pietrogregorini** [comment] 2017-11-26 10:19
Not working for me in MacBookPro 5,3. Can someone fix this?

**Comment by HackintoshHD** [comment] 2017-11-26 16:53
> The app can be installed and seems to work in a MacBookPro 5,3 with High Sierra, though it doesn't show the GPU name nor the switch between Integrated and Discrete cards works, so basically useless.
> 
> Can someone fix this, please?

@pietrogregorini: Your MacBookPro5,3's GPU name will probably be recognized if you install [a newer build from Steve Schow's gfxCardStatus fork, e.g. 2.4.4i](https://github.com/steveschow/gfxCardStatus/releases).

However, the app's essential, crucial feature - **switching from discrete to external GPU** - will remain impossible on MacBookPro5,2 and 5,3 with both Cody Krieger's last gfxCardStatus release and Steve Schow's recent builds from his fork (High Sierra seems to have broken it).

Any information on how to fix that would indeed be highly appreciated!

**Comment by pietrogregorini** [comment] 2017-11-26 18:56
@HackintoshHD Unfortunately neither Steve Schow's fork works for me. It doesn't show up the GPU name, nor switch between the cards.

![schermata 2017-11-26 alle 19 52 21](https://user-images.githubusercontent.com/3169323/33243300-bd6f282e-d2e3-11e7-8041-846a7456d747.png)

**Comment by HackintoshHD** [comment] 2017-11-29 19:47
@pietrogregorini Sorry to hear that - I had assumed your MacBookPro5,3's behaviour would be comparable to my 5,2's, where the cards, despite being unable to switch between them, are at least recognised when using one of the newer builds by Steve Schow.

**Comment by Sine-Audio** [comment] 2017-12-02 22:15
That's weird. It's working fine under latest High Sierra (10.13.1) with my 15" MBP Late 2016.

**Comment by pietrogregorini** [comment] 2017-12-05 20:47
@Sine-Audio Because your machine is supported by High Sierra, so probably the Nvidia drivers are updated for that machine which is relatively recent. Mine is an unsupported machine, such as the one of @HackintoshHD though we can run High Sierra through a patch tool. This tool was perfect also under Sierra, which was also an unsupported update for our MBPs, but with this new version it needs some refinements.

**Comment by m1nd7r1p** [comment] 2018-02-13 18:13
mid-2010 MPB on High Sierra (10.13.3): gfx is still not working correctly. It will run and appears to work correctly, eg the display will blink with changes to integrated-only, but still switches in response to apps including Safari when doing something as simple as browsing Amazon. The app has even been observed to switch from integrated-only to discreet-only without any input or any running app. Since I have the dreaded hardware problem with multiple daily crashes, a fix would be greatly appreciated.

**Comment by eapostol** [comment] 2018-03-06 15:24
+1 vote for this issue to be resolved. I am running macOS Sierra only , MBP mid-2010 but the OS is constantly asking to update now to high sierra. Would suggest to all in the meantime to backup their current copies of their OS / system with sierra installed and go no further.

**Comment by psalaberria002** [comment] 2018-04-03 16:29
I am having issues in High Sierra also. It crashes very often.

**Comment by eapostol** [comment] 2018-04-03 16:39
@psalaberria002 yeah, the only solution I have at this point is to maintain Sierra and not upgrade, until someone takes a moment to take a look at the software. I have had it running very well with just Sierra and gfxCardStatus 2.4.4i . Also note for second monitors and such I don't use my old miniport plug, I use a USB to HDMI converter. seems to offset the risk of crashes.

**Comment by mikesmithmike** [comment] 2018-04-03 22:41
My MBP Retina Mid 2012 now won't let me force "integrated only" after upgrading to HS.

**Comment by m1nd7r1p** [comment] 2018-04-04 16:10
My 15 MBP mid-2010 lets me force integrated-only in high Sierra (as in it throws no errors) but the setting doesn’t stick, apps can still switch to the discrete gpu.

**Comment by mobimation** [comment] 2018-04-18 08:26
While at it, can any of you hint what may be my issue ?  (Macbook Pro 17" late 2011)

When I have an external monitor connected, the display looks perfectly ok on the external monitor, and as I understand both the external and internal LCD run with the Nvidia graphics in that mode.  My problem is the **internal LCD** show green flickering / dithered artifacts in that mode, typically beginning after the laptop has warmed up from cold.  I assumed it would be a GPU failure but a reputed repair shop says "if it looks ok on the external monitor then it's not the GPU".  

I tried gfxCardStatus and with the external monitor disconnected it can switch the internal LCD to "Integrated Only" and then all artifacts disappear on the LCD, its display then appear perfectly normal !

If I switch back to "Discrete only" then the artifacts are back on the LCD (with or without an external monitor  connected).

So what would you suggest be worth troubleshooting ?

**Comment by m1nd7r1p** [comment] 2018-04-18 08:54
My understanding is that gfxCardStatus has been deprecated, as the issue is a bad transistor on the logic board. That transistor may sit between the GPU and the laptop display, given your description that the GPU operates just fine on an external display. There’s a different program cited by the gfx author on a page I found that forces this transistor to operate in only one of four possible states; when I installed that my kernel panics stopped. I’m sorry I don’t have specific names of these pages or the program, I did this some time ago and am no longer using that laptop. Google is your friend here. I even found a YouTube video by an Apple repair person  showing the exact transistor that needs replaced, with a description of the transistor needed to fix the problem. Do some searching and I’m sure you’ll find it, it wasn’t that hard to find. I decided the time and money weren’t worth it but you might decide otherwise.

**Comment by CodySchrank** [comment] 2018-04-19 06:30
Hey guys the current version was also kind of buggy for me so I rewrote the program in swift and made a bunch of changes to it.  I only did this because it seems like cody is no longer maintaining gfxCardStatus as much as he used to and I really need this utility.  Obviously its nowhere near the level of gfxCardStatus yet but its getting there.  Currently you have to make it from source but I'm going to make an easier way to download soon.  I think it only supports macs 2011+  (I have no way of testing this).  Anyways if you're having problems with gfxCardStatus give [mine](https://github.com/CodySchrank/gSwitch) a try

**Comment by eapostol** [comment] 2018-04-19 14:51
Hi @CodySchrank - thanks for the posting. I have forked your repo and will try it out on macbook pro (mid-2010) - likely over the weekend. Will let you know if there are any issues. cheers!

**Comment by CodySchrank** [comment] 2018-04-19 18:10
@eapostol In gfxCardStatus cody makes deliberate changes when a macbook is 2010 or older ("legacy") and I'm not exactly sure why, or if its still even needed.  If mine doesn't work maybe you can help me test it?

**Comment by jaydedm** [comment] 2018-04-22 19:29
My mid-2012 retina macbook pro also won't force integrated graphics, which is a shame because my discrete GPU is causing GPU panics and crashes. Hoping somebody finds a fix and posts in here soon@

**Comment by eapostol** [comment] 2018-04-23 02:35
@CodySchrank sure I can take a look into it. I have had very infrequent GPU panics since installing the last version ( @steveschow 's fork  mentioned earlier) but they do occur (my MBP mid-2010 basically never shuts down any more and only goes to sleep.

**Comment by codykrieger** [comment] 2018-10-18 05:47
Tracking in #310; closing.

**Closed by codykrieger** 2018-10-18 05:47 UTC
