### ISSUE TITLE
Run at startup as Integrated Only mode . It possible ?

### ISSUE THREAD

**Issue by staska012** [codykrieger/gfxCardStatus#275] opened 2017-04-10 23:26 UTC
please help to find a way to run gfxCardStatus app in Integrated Only mode.
after log out and restart  , the program run at Dynamics's switched .

**Comment by codykrieger** [comment] 2017-04-10 23:30
Duplicate of #150.

**Closed by codykrieger** 2017-04-10 23:30 UTC

**Comment by staska012** [comment] 2017-04-10 23:36
how can i run this patch? https://github.com/steveschow/gfxCardStatus/releases/tag/v2.4.3i

 the app inside not working with auto save ...
