### ISSUE TITLE
Information mismatch between status and choice

### ISSUE THREAD

**Issue by hericius** [codykrieger/gfxCardStatus#289] opened 2017-08-17 07:02 UTC
Hello,

I observe that there is a mismatch between the card name in use (status information) and the card activated.

The activated card doesn't correspond to the activated card when I select 'Integrated only', as shown below:

![screen shot 2017-08-17 at 08 53 37](https://user-images.githubusercontent.com/3530574/29399716-a01b5a6c-832a-11e7-8d3e-fe99dda0b34a.png)

System information:
     MackBook Pro Retina 15", mid 2014
     MacOS 10.12.6
     Intel Iris Pro & NVIDIA GeForce GT 750M

My 2 cents to this excellent small tool,
André,

**Comment by codykrieger** [comment] 2017-08-17 07:05
Dupe of #103.

**Comment by codykrieger** [comment] 2017-08-17 07:05
(And thanks for the report!)

**Closed by codykrieger** 2017-08-17 07:05 UTC

**Comment by hericius** [comment] 2017-08-17 07:21
Sorry for the dupe.
