### ISSUE TITLE
2016 MBP 15 in with gfx2.5 BigSur 11.3

### ISSUE THREAD

**Issue by admirllq** [codykrieger/gfxCardStatus#366] opened 2021-04-27 06:47 UTC
I can't force my MBP to run on integrated gpu only. When I selected it in the gfx menu, it automatically jumped to the discrete gpu. With the new bigsur, my safari is weirdly keeping calling for discrete gpu. I want to run on integrated gpu only to save some power, any help? Thank you.

**Comment by codykrieger** [comment] 2021-04-29 00:53
Dupe of #310.

**Closed by codykrieger** 2021-04-29 00:53 UTC
