### ISSUE TITLE
Graphics Processor Choice Doesn't "Stick"

### ISSUE THREAD

**Issue by lybanon** [codykrieger/gfxCardStatus#200] opened 2015-05-17 20:23 UTC
15-inch Mid 2010 MacBook Pro, OS X 10.10.3, latest version of gfxCardStatus

If I choose "Integrated Only," sometimes the system (presumably) switches to the discrete GPU on its own.  When that happens, the gfxCardStatus menu bar indicator shows "Discrete Only."  I can switch back to Integrated Only manually unless some program is running that prevents it.

**Comment by codykrieger** [comment] 2015-05-18 01:30
Dupe of #107.

**Closed by codykrieger** 2015-05-18 01:30 UTC
