### ISSUE TITLE
gfxCardStatus its own dependency

### ISSUE THREAD

**Issue by kterzopoulos** [codykrieger/gfxCardStatus#281] opened 2017-06-13 04:53 UTC
gfxCardStatus is not letting me change status!
(is that a circular argument?)

I have the MBP (17-inch, Early 2011) with the buggy AMD Radeon. It's already been replaced with the Apple program, but the issue has resurfaced and now my machine is classified as "legacy" and no longer supported.

Can'y I turn this thing off somehow?

thanks

**Comment by codykrieger** [comment] 2017-06-20 16:44
Dupe of #162.

**Closed by codykrieger** 2017-06-20 16:44 UTC
