### ISSUE TITLE
5600M not switchable

### ISSUE THREAD

**Issue by ltwin8** [codykrieger/gfxCardStatus#367] opened 2021-05-12 11:52 UTC
Installed v2.5 on MacBook Pro 16", GPU: 5600M.

Problem:
select integrated graphic: it switches to dedicated and displays "d" 
select dedicated graphic: it switches to dedicated and displays "d" 
select automatic graphic: it switches to integrated and displays "i" until macOS "itself" required dedicated

**Comment by cibimo** [comment] 2021-06-20 15:24
same problem

**Comment by RoadToDream** [comment] 2021-07-09 21:32
@cibimo @david1asher @ltwin8 please consider this build
[gfxCardStatus.zip](https://github.com/codykrieger/gfxCardStatus/files/6794009/gfxCardStatus.zip)

**Comment by codykrieger** [comment] 2021-07-10 01:55
This is likely a duplicate of #331, so we'll track this there.

**Closed by codykrieger** 2021-07-10 01:55 UTC

**Comment by IslandOwnerHuang** [comment] 2022-04-23 00:38
Same here
