### ISSUE TITLE
gfxCardStatus integrated-only logic error

### ISSUE THREAD

**Issue by steveschow** [codykrieger/gfxCardStatus#237] opened 2016-04-25 18:25 UTC
Some apps when they quit are switching to discrete graphics as they quit.

If gfxCardSatus is set to dynamic switching, this is no problem, it will subsequently switch back to integrated mode as soon as the app is completely exited. (assuming no other dependent apps)

The problem is that when the gfxCardStatus is trying to use “integrated-only” mode.  This mode is tracked internally by setting the Dynamic-switching flag to off.  Having that flag off applies to both integrated-only mode and discrete-only mode.  Therein lies the rub.

When an app forces to discrete mode on exit, the dynamic switching flag is left unchanged (OFF) and the user returns to OSX permanently in discrete-only mode, rather then integrated-only mode.  This is very undesirable and makes integrated-only mode unusable.

A proper fix for this logic error should be to detect that when an app forces to discrete mode on exit while in integrated-only mode, the dynamic switching flag should be temporarily turned on, so that dynamic switching can switch back to integrated mode as soon as possible.  Ideally, gfxCardStatus would also detect when it goes back to integrated, and then switch the dynamic-switching flag back off again when the user is hoping for integrated-only functionality.

Yes its true that this would not be true 100% integrated-only, as some apps would briefly switch to discrete mode on exit.  However what is happening now is really unusable as integrated-only mode often causes the entire machine to be switched to discrete-only mode permanently rather then just briefly on exit.

I would fix this myself but I am unable to get the current release to build(see other ticket).

**Comment by codykrieger** [comment] 2016-04-25 18:30
This is a duplicate of #107.

**Closed by codykrieger** 2016-04-25 18:30 UTC

**Comment by steveschow** [comment] 2016-04-25 19:03
their fix was the wrong.  Please read my suggestion more carefully

**Comment by codykrieger** [comment] 2016-04-25 19:09
Calling this a logic error is disingenuous—gfxCardStatus correctly realizes when the system switches to the discrete GPU and updates its state. This is not a gfxCardStatus bug, per se.

The fix in #107 does exactly what users would expect: when gfxCardStatus' state does not match the actual, desired state of the system, it forces the system back to Integrated Only. Doing what you suggest and turning on Dynamic Switching in this case would be just as confusing as the behavior in gfxCardStatus today.

**Comment by steveschow** [comment] 2016-04-25 19:12
its a logic error in that so called "integrated-only" mode is totally broken.  I don't mean to offend, just trying to offer a very easy solution.

**Comment by steveschow** [comment] 2016-04-25 19:13
and not the current version is totally broken, that other hack...maybe wasn't pushed into the release because you didn't like what they did I don't know, but the current release is broken still

**Comment by codykrieger** [comment] 2016-04-25 19:13
I'm aware.

**Comment by steveschow** [comment] 2016-04-25 19:15
also if you think about what is happening now...is that those products trying to switch to discrete mode, but is is gfxCardstatus and this "logic error" that is putting the system into discrete-only when the user never asked for that nor was that the assumption by the exiting app

**Comment by steveschow** [comment] 2016-04-25 19:15
note the  distinction between discrete mode and discrete-only mode

**Comment by codykrieger** [comment] 2016-04-25 19:17
You're wrong. OS X is responsible for 100% of that behavior, not gfxCardStatus. gfxCardStatus merely thinks it's in Discrete Only mode because the system is telling it:

1. The discrete GPU is on; and
2. Automatic graphics switching is turned off

**Comment by steveschow** [comment] 2016-04-25 19:18
gfxCardStatus is using dynamic switching flag...OSX moves to discrete without changing the flag...therefore since gfxCardStatus turned off that flag.....the system becomes discrete-ONLY.  Yes gfxCardStatus is causing this problem

**Comment by steveschow** [comment] 2016-04-25 19:19
When I have the machine in dynamo switching mode..this never happens...the system remains in dynamic switching mode.  The problem only occurs when I try to use integrated only mode using gfxCardStatus...then it ends up stuck in discrete only mode

**Comment by codykrieger** [comment] 2016-04-25 19:20
You have *no idea* what you're talking about. I'm not wasting any more of my time entertaining this pointless discussion.
