### ISSUE TITLE
Weird problem with GFX

### ISSUE THREAD

**Issue by madso1234** [codykrieger/gfxCardStatus#262] opened 2017-01-11 16:41 UTC
Hello, i get at weird problem when trying to switch to integrated only. It says i can't switch to integrated while gfxCardStatus is open. Makes it kinda difficult. 
See picture. :)

![screen shot 2017-01-11 at 17 40 16](https://cloud.githubusercontent.com/assets/25061268/21857256/1e0c8c18-d825-11e6-9ef0-f163bd382e81.png)

**Comment by madso1234** [comment] 2017-01-11 16:42
i know it says creative cloud also, but it doesn't change anything when i close it.

**Comment by codykrieger** [comment] 2017-01-13 10:05
Dupe of #240.

**Closed by codykrieger** 2017-01-13 10:05 UTC
