### ISSUE TITLE
Catalina - generic "card" name in menu but correct notofications

### ISSUE THREAD

**Issue by lukpep** [codykrieger/gfxCardStatus#334] opened 2020-04-17 17:44 UTC
system version:
![image](https://user-images.githubusercontent.com/2960580/79598097-ac028800-80e3-11ea-936f-10aada2b0005.png)

![image](https://user-images.githubusercontent.com/2960580/79598152-c2a8df00-80e3-11ea-83ef-16db637c2a37.png)

but while switching cards correct card name is set on the notification

**Comment by codykrieger** [comment] 2020-04-18 01:26
Thanks for the report. This is a dupe of #99.

**Closed by codykrieger** 2020-04-18 01:26 UTC
