### ISSUE TITLE
macbook pro Mojave bug

### ISSUE THREAD

**Issue by Mickelbil84** [codykrieger/gfxCardStatus#308] opened 2018-10-01 21:01 UTC
Hey, I really appreciate gfxcardstatus, its feature allows my Macbook keep working since my nvidia GPU crashes the mother board (you probably heard about the mid 2012 manufacture issues..). However, there is a bug since i upgraded to OSX Mojave, it wont let it stay on the 'Integrated Only' feature, it always jumps to  'Discrete Only'.. PELASE solve this, i'm really lost without it, can't find any alternatives, i will really appreciate a solution

**Comment by codykrieger** [comment] 2018-10-01 21:05
Dupe of some combination of #282 / #242 / #240.

**Closed by codykrieger** 2018-10-01 21:05 UTC
