### ISSUE TITLE
Menu shows "Discrete Only" while active card + icon is the integrated one

### ISSUE THREAD

**Issue by bligny** [codykrieger/gfxCardStatus#290] opened 2017-08-18 09:15 UTC
![image](https://user-images.githubusercontent.com/19853549/29452332-381b089a-8406-11e7-93a5-e767ab4b8b99.png)

**Env:**
Mac Book Pro Early 2011
MacOs Sierra 10.12.6

**Comment by codykrieger** [comment] 2017-08-18 18:07
Dupe of #103.

**Closed by codykrieger** 2017-08-18 18:07 UTC
