### ISSUE TITLE
Forcing integrated card not working

### ISSUE THREAD

**Issue by carlosbaraza** [codykrieger/gfxCardStatus#368] opened 2021-06-08 16:46 UTC
I'm not sure why, but it is not possible to change to integrated graphics on my MacBook Pro (15-inch, 2019).

![Kapture 2021-06-08 at 17 44 43](https://user-images.githubusercontent.com/1270425/121225329-522dc600-c881-11eb-8c9a-b6ae2fa64691.gif)

Anyone has a workaround?

**Comment by bpress** [comment] 2021-06-16 05:34
The very same issue is happening on my MacBook Pro 16 2019. Switching from dynamic to integrated activates the Radeon card. There's no way to activate the Intel card even with the mac idling (no apps with visible windows running other than the Finder).

**Comment by renesansz** [comment] 2021-07-05 13:55
same issue here. I'm on Macbook Pro 15" (Mid-2015) - Dual GPU, MacOS Big Sur 11.4.

**Comment by RoadToDream** [comment] 2021-07-09 18:28
> same issue here. I'm on Macbook Pro 15" (Mid-2015) - Dual GPU, MacOS Big Sur 11.4.

@renesansz @bpress @carlosbaraza  please consider this build 

[gfxCardStatus.zip](https://github.com/codykrieger/gfxCardStatus/files/6793277/gfxCardStatus.zip)

**Comment by renesansz** [comment] 2021-07-10 00:16
@RoadToDream it seems it's broken
![image](https://user-images.githubusercontent.com/4784170/125146164-183d3180-e157-11eb-8e4d-9032336daacd.png)

**Comment by RoadToDream** [comment] 2021-07-10 00:19
> @RoadToDream it seems it's broken
> 
> ![image](https://user-images.githubusercontent.com/4784170/125146164-183d3180-e157-11eb-8e4d-9032336daacd.png)
> 
> 

@renesansz  Hahaha that's embarrassing.. My bad 

Let me sign this package and re-upload.

**Comment by RoadToDream** [comment] 2021-07-10 00:46
@renesansz I have updated the file and you may give it a try. 
Wish this build works for you(I may upload a validated build several days later once Apple fixed my developer account, but till now you may need to approve it in settings app). 

[gfxCardStatus.app.zip](https://github.com/codykrieger/gfxCardStatus/files/6794404/gfxCardStatus.app.zip)

**Comment by codykrieger** [comment] 2021-07-10 01:51
@RoadToDream What changes have you made in this build?

**Comment by codykrieger** [comment] 2021-07-10 01:55
This is likely a duplicate of #331, so we'll track this there.

**Closed by codykrieger** 2021-07-10 01:55 UTC

**Comment by RoadToDream** [comment] 2021-07-10 02:30
> @RoadToDream What changes have you made in this build?

Hi codykrieger! 
Thank you for brining this useful app, this is the best among all similar tools(especially it can preserve hardware info even after applying the callback) 

Original implementation is perfect and it does perform the forcing switch, but the UI does not perform correspondingly. 
isOnIntegratedOnlyMode in GSMux will always return a false as newer Macs will return NO to (self.isUsingOldStyleSwitchPolicy || [GSGPU is2010MacBookPro]). 
This will affect the setstate operation in GSMenuController.

**Comment by RoadToDream** [comment] 2021-07-10 02:33
> This is likely a duplicate of #331, so we'll track this there.

Of course that might not be the cause for some other similar issues, but I would just like to report that this causes the undesirable behavior on my 2017 15'' and 2019 16'' Mac.

**Comment by codykrieger** [comment] 2021-07-10 02:52
@RoadToDream Oh, wow, that's a really silly bug. Thanks for finding that! I unfortunately no longer have a dual-GPU machine to test with, but if you'd like to send a pull request, I'd be happy to accept it.

**Comment by RoadToDream** [comment] 2021-07-10 03:11
> @RoadToDream Oh, wow, that's a really silly bug. Thanks for finding that! I unfortunately no longer have a dual-GPU machine to test with, but if you'd like to send a pull request, I'd be happy to accept it.

Of course! Would be honored
Pull request submitted.  
isOnIntegratedOnlyMode in GSMux remains the same as I don't want to hurt users of old Mac. Only MenuController is modified, which should be enough

**Comment by bpress** [comment] 2021-07-10 07:39
@RoadToDream I've just tested it on my MacBook Pro 16 2019 - Big Sur but still no success:

![image](https://user-images.githubusercontent.com/5276671/125155838-9b17b980-e162-11eb-896c-1d7d2ce1213e.png)

If I leave it on automatic, it show the "i" icon; if I try to force a manual switch to integrated or discrete, it always switches to the Radeon card.

**Comment by RoadToDream** [comment] 2021-07-10 07:52
> @RoadToDream I've just tested it on my MacBook Pro 16 2019 - Big Sur but still no success:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/5276671/125155838-9b17b980-e162-11eb-896c-1d7d2ce1213e.png)
> 
> 
> 
> If I leave it on automatic, it show the "i" icon; if I try to force a manual switch to integradet or discrete, it always switches to the Radeon card.

That's really sad. I am sorry that I can not reproduce this error on my 2019 16. 

Would you like to check Activity monitor-energy, is it showing Integrated card or Discrete Card after you force a manual switch to integrated?

**Comment by bpress** [comment] 2021-07-10 08:01
> That's really sad. I am sorry that I can not reproduce this error on my 2019 16.
> 
> Would you like to check Activity monitor-energy, is it showing Integrated card or Discrete Card after you force a manual switch to integrated?

@RoadToDream sure, here are the 3 cases

Automatic:
![image](https://user-images.githubusercontent.com/5276671/125156394-7cff8880-e165-11eb-8a2a-e99d30c29807.png)

Discrete:
![image](https://user-images.githubusercontent.com/5276671/125156426-986a9380-e165-11eb-9624-15d1b7027c98.png)

Integrated (still using discrete):
![image](https://user-images.githubusercontent.com/5276671/125156446-b506cb80-e165-11eb-89f4-69b9a2338549.png)

**Comment by RoadToDream** [comment] 2021-07-10 15:23
@bpress Thank you! 
That's a weird error and I have to say I have no idea why it happened. 

I will try to debug, but that error may related to something more complicated.

**Comment by bpress** [comment] 2021-07-12 06:03
@RoadToDream 
> I will try to debug, but that error may related to something more complicated.

Ok, let me know if I can be of any help.
