### ISSUE TITLE
Icon is offset on Big Sur

### ISSUE THREAD

**Issue by switz** [codykrieger/gfxCardStatus#348] opened 2020-12-11 19:53 UTC
Just upgraded to Big Sur and noticed the icon was offset in my menu bar

<img width="124" alt="image" src="https://user-images.githubusercontent.com/990166/101948821-ac92e600-3bc0-11eb-91ab-75c119fd5b90.png">

**Comment by codykrieger** [comment] 2020-12-11 23:13
Dupe of #336, which is fixed in the v2.5 beta. Download here: https://github.com/codykrieger/gfxCardStatus/releases/download/v2.5b4/gfxCardStatus-2.5b4.zip

**Closed** 2020-12-11 23:14 UTC
